#!/usr/bin/env bash

VM_HOSTNAME=$1
VM_TEMPLATE=$2

if [ -x $VM_HOSTNAME ]; then
  echo "Requires argument hostname"
  echo "Usage: $0 [HOSTNAME] [TEMPLATE]"
  exit 1
fi

if [ -x $VM_TEMPLATE ]; then
  echo "Requires argument template"
  echo "Usage: $0 [HOSTNAME] [TEMPLATE]"
  exit 1
fi

echo "Starting build of: $VM_HOSTNAME"

bash ./scripts/sysprep.sh $VM_HOSTNAME $VM_TEMPLATE

if [ $? != 0 ]; then
  echo "Could not create image!"
  exit 2
fi

bash ./scripts/build_template.sh $VM_HOSTNAME

if [ $? != 0 ]; then
  echo "Could not create template!"
  exit 2
fi

mv $VM_HOSTNAME.qcow /var/lib/libvirt/images/$VM_HOSTNAME.qcow

echo "Starting and defining $VM_HOSTNAME"
virsh define $VM_HOSTNAME.xml > /dev/null
virsh start $VM_HOSTNAME > /dev/null
